# ==============================================================================
# 01 - IDENTITY AND PERMISSIONS
# This file establishes the Kubernetes identity that Vault will trust.
# ==============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: app-namespace

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-ksa
  namespace: app-namespace

---
# POC "GOTCHA" ALERT: The Auth Delegator
# Vault needs to ask the Kubernetes API: "Is this Service Account token valid?"
# By default, Service Accounts are denied permission to ask the API that question.
# We must explicitly grant our app account the 'system:auth-delegator' role
# so Vault can successfully verify the token and avoid a 403 Permission Denied.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-ksa-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: backend-ksa
  namespace: app-namespace