# ==============================================================================
# 02 - THE VAULT SECRETS OPERATOR (VSO) BRIDGE
# This file tells the operator how to escape Minikube, talk to Vault, 
# and translate the secret into a format the Go app understands.
# ==============================================================================

# Step 1: The Network Map
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: host-vault-connection
  namespace: app-namespace
spec:
  # External Vault Routing
  # Because Vault is running natively on Windows (not inside Minikube), 
  # VSO cannot use 'localhost'. We must use Minikube's special internal DNS
  # to break out of the VM and reach the host machine's port 8200.
  address: http://host.minikube.internal:8200

---
# Step 2: The Authentication Handshake
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: app-namespace
spec:
  vaultConnectionRef: host-vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-role
    serviceAccount: backend-ksa

---
# Step 3: The Secret Fetch & Translation
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: gcp-firebase-secret
  namespace: app-namespace
spec:
  vaultAuthRef: vault-auth
  mount: gcp
  path: static-account/my-app-key-rotator/key
  destination:
    create: true
    name: firebase-sa-k8s-secret
    # POC "GOTCHA" ALERT: Base64 Decoding
    # Vault's GCP engine outputs the key as a Base64 encoded string.
    # If passed directly, the Go app crashes trying to parse 'ew...' as JSON.
    # We use VSO's built-in Sprig templating engine to intercept the string,
    # decode it using 'b64dec', and output pure JSON to 'firebase-sa.json'.
    transformation:
      templates:
        firebase-sa.json:
          text: '{{ .Secrets.private_key_data | b64dec }}'